name: SoupFFA
main: SoupFFA\SoupFFA
version: 1.8.1
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: McpeBooster
website: twitter.com/McpeBooster

commands:
  soupffa:
    description: Join SoupFFA directly per Command
