name: PeacefulSpawn
main: LDX\PeacefulSpawn\Main
version: 2.6
api:
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
load: POSTWORLD
author: "LDX"
website: "https://github.com/LDX-MCPE/PeacefulSpawn"
commands:
  ps:
    description: Toggles PeacefulSpawn's protection
    usage: "/ps"
    permission: peacefulspawn.toggle
permissions:
  peacefulspawn:
    description: "Allows access to all PeacefulSpawn features."
    default: op
    children:
      peacefulspawn.toggle:
        description: "Allows the user to toggle spawn protection."
        default: op
