name: MaskShop
main: MASKshop\Main
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 1.1
author: PLUGPLUS
Translate: Russian to English by xXNiceYT

commands:
 mask:
  aliases: ["maskshop"]
  description: "Mask Shop Command"
