name: PlayerVaults
main: PlayerVaults\PlayerVaults
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: VMPE Development Team
version: 3.0.1
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  playervaults.vault.1:
    default: true
