main: aliuly\grabbag\Main
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 2.4.0-2
author: aliuly
website: https://github.com/Muirfield/GrabBag
softdepend: FastTransfer
