name: KitUI
author: Infernus101
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: Infernus101\KitUI\Main
version: 1.0.1
permission: # kit permissions - kit.<kit name>
 kit.command:
  description: kit command!
  default: true
commands:
  kit:
    description: Kit UI!